### ISSUE TITLE
Lasers can activate Schrödinger's cubes from sides and pass through

### ISSUE THREAD

**Issue by Komos63** [AxoLabs/BEE2-Axos-Packages#10]
### BEEMod version
4.43.0 both app and packages

### UCP version
1.5

### Describe the bug
Your fix for catcher Schrödinger cubes letting lasers through while also being powered ~~does not function properly~~ *has a side effect*. 
![27AAD4A6-29CB-4EAC-8F21-2084C4FC6225](https://user-images.githubusercontent.com/78902172/231406661-99f8974e-2dcd-4a9d-92d5-b45fb1ae0516.png)
![D238C065-D1C2-4424-BCF5-B755B22BAD61](https://user-images.githubusercontent.com/78902172/231406699-6f5d3d92-07a8-4c73-927d-fda108d484b6.png)

### Steps to reproduce
1. Place catcher cube inside of any laser
2. Point emitter cube just slightly to the edge of the catcher cube
3. Very slowly move the catcher cube away from the original laser while staying parralel to the laser emitting from the emitter cube
-> Catcher cube gets powered, laser goes past cube

### Additional Information
I think the laser relay inside of the cube is slightly larger than the cube itself // *No, there's no relay inside the cube.*
![F9CD2DE9-F6DB-4924-92EF-75AAAE6E5614](https://user-images.githubusercontent.com/78902172/231411130-31747021-7230-49b2-8182-06b60a301e1d.png)

**Comment by RobinRattus** [comment]
The laser relay hitbox being larger than the cube on the sides also explains why catcher cubes don't activate when lasers point on their edges.

**Comment by AxoLabs** [comment]
I was certain this will be an issue even before I checked that it is an issue, and no, it is not caused by what you assumed to be the cause. The issue isn't the relay's hitbox, as of now, I'm  certain that's something I can't change without a custom model. The cube is essentially *covered* in laser relays on each side, but the side effect is that you can activate it from sides, and have the laser pass through. I could fix this by covering the cube in a ton of `func_brush`es that block lasers or something along the lines of that, but it'd cause even more problems, and kind of like with floating reflector cubes, it's just on the player not to abuse this. As such, this issue will not be fixed any time soon, if ever.
