### ISSUE TITLE
Gel on Schrödinger's cubes is barely/not visible at all

### ISSUE THREAD

**Issue by Komos63** [AxoLabs/BEE2-Axos-Packages#5]
### BEEMod version
2.4.43.0

### UCP version
1.5 Beta 7 // _Confirmed to affect previous and ~~later versions as well~~ partially mitigated in update 1.6._

### Describe the bug
Painting a Schrödinger Cube works mostly as intended, the effects do work however you cannot see the paint.

### Steps to reproduce
Place Gel and Schrödinger Cube
Paint Schrödinger Cube using said Gel
Gel works but invisible
### Additional Information
None

**Comment by AxoLabs** [comment]
Known issue, the green overlay makes it barely visible, just like I am aware of gel having no effect on catcher cubes. I might fix this if I ever choose to give the cubes custom models/textures, but that is unlikely to happen any time soon.

**Comment by AxoLabs** [comment]
The issue will be partially fixed in 1.6. I have made emitter cubes slightly brighter, so it's possible to see the gel now. As for catcher cubes not having the paint texture applied to them at all, this will likely take a long time to fix, as they use a non-standard cube type (6) which does not have gel skins defined. Although, maybe if I changed the cube type to antique after it spawns, it would work...
